# Numpy Operations on CSV file

In [2]:
import numpy as np

# Load data from CSV file
data= np.loadtxt("numpylab1.csv", delimiter=",",dtype=str)
print(data)
print()

[['Name' 'Gender' 'DOB' 'Maths' 'Physics' 'Chemistry' 'English' 'Biology'
  'Economics' 'History' 'Civics']
 ['John' 'M' '05-04-1988' '55' '45' '56' '87' '21' '52' '89' '65']
 ['Suresh' 'M' '04-05-1987' '75' '96' '78' '64' '90' '61' '58' '2']
 ['Ramesh' 'M' '25-05-1989' '25' '54' '89' '76' '95' '87' '56' '74']
 ['Jessica' 'F' '12-08-1990' '78' '96' '86' '63' '54' '89' '75' '45']]



In [3]:
# Creating Matrix
matrix1=np.loadtxt("numpylab1.csv", delimiter=",",skiprows=1,usecols=(3,4,5,6))
print(matrix1)

print()

matrix2=np.loadtxt("numpylab1.csv", delimiter=",",skiprows=1,usecols=(7,8,9,10))
print(matrix2)

[[55. 45. 56. 87.]
 [75. 96. 78. 64.]
 [25. 54. 89. 76.]
 [78. 96. 86. 63.]]

[[21. 52. 89. 65.]
 [90. 61. 58.  2.]
 [95. 87. 56. 74.]
 [54. 89. 75. 45.]]


In [4]:
# Matrix addition
result_addition=np.add(matrix1,matrix2)
print("MAtrix addition is:")
print(result_addition)

print()

# Matrix subtraction
result_subtraction=np.subtract(matrix1,matrix2)
print("MAtrix subtraction is:")
print(result_subtraction)

print()

# Matrix multiplication Elementwise
result_multiplication=np.multiply(matrix1,matrix2)
print("MAtrix elementwise multiplication is:")
print(result_multiplication)

print()

# Matrix multiplication dot product
result_multiplication=np.matmul(matrix1,matrix2)
print("MAtrix dot product multiplication is:")
print(result_multiplication)

print()
 

MAtrix addition is:
[[ 76.  97. 145. 152.]
 [165. 157. 136.  66.]
 [120. 141. 145. 150.]
 [132. 185. 161. 108.]]

MAtrix subtraction is:
[[ 34.  -7. -33.  22.]
 [-15.  35.  20.  62.]
 [-70. -33.  33.   2.]
 [ 24.   7.  11.  18.]]

MAtrix elementwise multiplication is:
[[1155. 2340. 4984. 5655.]
 [6750. 5856. 4524.  128.]
 [2375. 4698. 4984. 5624.]
 [4212. 8544. 6450. 2835.]]

MAtrix dot product multiplication is:
[[15223. 18220. 17166. 11724.]
 [21081. 22238. 21411. 13719.]
 [17944. 19101. 16041. 11739.]
 [21850. 23001. 22051. 14461.]]



In [5]:
# Horizontal stacking
horizontal_stack=np.hstack((matrix1,matrix2))

# Vertical stacking
vertical_stack=np.vstack((matrix1,matrix2))

print("horizontal_stack is: ")
print(horizontal_stack)
print()
print("vertical_stack is :")
print(vertical_stack)

horizontal_stack is: 
[[55. 45. 56. 87. 21. 52. 89. 65.]
 [75. 96. 78. 64. 90. 61. 58.  2.]
 [25. 54. 89. 76. 95. 87. 56. 74.]
 [78. 96. 86. 63. 54. 89. 75. 45.]]

vertical_stack is :
[[55. 45. 56. 87.]
 [75. 96. 78. 64.]
 [25. 54. 89. 76.]
 [78. 96. 86. 63.]
 [21. 52. 89. 65.]
 [90. 61. 58.  2.]
 [95. 87. 56. 74.]
 [54. 89. 75. 45.]]


In [6]:
# Generating a sequence from 0 to 9
sequence=np.arange(10)
print("Custom sequence:")
print(sequence)
print()

# Arithmatic Opeartions

mean=np.mean(matrix1)
std_deviation=np.std(matrix1)

# Statistical Operations
sum=np.sum(matrix1)
min_value=np.min(matrix1)
max_value=np.max(matrix1)

print("Mean:",mean)
print("Standard deviation:",std_deviation)
print("Sum:",sum)
print("Min value:",min_value)
print("Max value:",max_value)


Custom sequence:
[0 1 2 3 4 5 6 7 8 9]

Mean: 70.1875
Standard deviation: 19.135107623162195
Sum: 1123.0
Min value: 25.0
Max value: 96.0


In [7]:
# Exponential Functions
result_exp=np.exp(matrix1)

#Logarithmic FUnctions
result_log=np.log(matrix1)

# Trignometric Functions
result_sin=np.sin(matrix1)
result_cos=np.cos(matrix1)

print("Exponential Functions:")
print(result_exp)
print()

print("Logarithmic Functions:")
print(result_log)
print()

print("Trignometric Functions:")
print("Sin value matrix is: ",result_sin)

print()

print("Cos value matrix is: ",result_cos)


Exponential Functions:
[[7.69478527e+23 3.49342711e+19 2.09165950e+24 6.07603023e+37]
 [3.73324200e+32 4.92345829e+41 7.49841700e+33 6.23514908e+27]
 [7.20048993e+10 2.83075330e+23 4.48961282e+38 1.01480039e+33]
 [7.49841700e+33 4.92345829e+41 2.23524660e+37 2.29378316e+27]]

Logarithmic Functions:
[[4.00733319 3.80666249 4.02535169 4.46590812]
 [4.31748811 4.56434819 4.35670883 4.15888308]
 [3.21887582 3.98898405 4.48863637 4.33073334]
 [4.35670883 4.56434819 4.4543473  4.14313473]]

Trignometric Functions:
Sin value matrix is:  [[-0.99975517  0.85090352 -0.521551   -0.82181784]
 [-0.38778164  0.98358775  0.51397846  0.92002604]
 [-0.13235175 -0.55878905  0.86006941  0.56610764]
 [ 0.51397846  0.98358775 -0.92345845  0.1673557 ]]

Cos value matrix is:  [[ 0.02212676  0.52532199  0.85322011  0.56975033]
 [ 0.92175127 -0.18043045 -0.85780309  0.39185723]
 [ 0.99120281 -0.82930983  0.51017704  0.82433133]
 [-0.85780309 -0.18043045 -0.38369844  0.98589658]]


In [11]:
# Copying array

dataset_copy=np.copy(data)
print("Dataset is: ")
print(dataset_copy)


Dataset is: 
[['Name' 'Gender' 'DOB' 'Maths' 'Physics' 'Chemistry' 'English' 'Biology'
  'Economics' 'History' 'Civics']
 ['John' 'M' '05-04-1988' '55' '45' '56' '87' '21' '52' '89' '65']
 ['Suresh' 'M' '04-05-1987' '75' '96' '78' '64' '90' '61' '58' '2']
 ['Ramesh' 'M' '25-05-1989' '25' '54' '89' '76' '95' '87' '56' '74']
 ['Jessica' 'F' '12-08-1990' '78' '96' '86' '63' '54' '89' '75' '45']]


array([['work_year', 'job_title', 'job_category', ..., 'work_setting',
        'company_location', 'company_size'],
       ['2023', 'Data DevOps Engineer', 'Data Engineering', ...,
        'Hybrid', 'Germany', 'L'],
       ['2023', 'Data Architect', 'Data Architecture and Modeling', ...,
        'In-person', 'United States', 'M'],
       ...,
       ['2021', 'Principal Data Scientist', 'Data Science and Research',
        ..., 'Remote', 'United States', 'L'],
       ['2020', 'Data Scientist', 'Data Science and Research', ...,
        'Remote', 'United States', 'S'],
       ['2020', 'Business Data Analyst', 'Data Analysis', ..., 'Remote',
        'United States', 'L']], dtype='<U40')